# Site settings
language:               "fa"
title:                  "فایبرنت"
description:            ""
url: http://fibernet.ir
google_analytics: 


# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "/assets/"
  - "/fast-charge/partials/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-jalali
  - jekyll-archives

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

# archive configuration
jekyll-archives:
  enabled:
  - tags
  layout: 'archive'
  permalinks:
    tag: "/blog/tag/:name/"

collections:
  tutorial:
    output: true
    permalink: "/:collection/:title/"

