# Site settings
language:               "fa"
title:                  "پارس فایبرنت"
description:            "پارس فایبرنت ارائه‌دهنده خدمات مرکز تماس و راهکارهای نرم‌افزاری و اینترنتی"
keywords: "فایبرنت , مرکز تماس , مرکز تلفن , برون سپاری , منشی مجازی , CRM , صدای مشتری"
url: http://parsfibernet.com
google_analytics: UA-105263568-1


# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Plugins
plugins:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]
